version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "niklasvh"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      rollup-plugins:
        patterns:
          - "@rollup/*"
      types:
        patterns:
          - "@types/*"
      playwright:
        patterns:
          - "@playwright/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
